name: Testing

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEBIAN }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 3.133.157.180 >> ~/.ssh/known_hosts

      - name: Add StrictHostKeyChecking to SSH Config
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Your Other Steps
        run: |
          # Your other deployment steps here
          ssh admin@3.133.157.180 'bash -s' <<'EOF'
          sudo apt update
          ip a
          sudo apt install docker.io -y
          sudo apt install git -y
          which docker
          docker images
          sudo chmod 777 /var/run/docker.sock
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
          docker rmi $(docker images)
          git clone https://github.com/Alien-X01/pr_final.git
          cd pr_final
          docker build -t final .
          docker run --name pr_final -d -p 8080:80 final
          cd ..
          sudo rm -r pr_final
          cd
          git clone https://github.com/Alien-X01/pr_script.git
          cd pr_script
          chmod 755 script
          ./script
          cd ..
          sudo rm -r pr_script
          sudo rm /var/www/html/index.html
          sudo sh -c "echo '<h1>Hello From Debian 01 </h1>' >/var/www/html/index.html"
          EOF
