name: Your Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MARIADB }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 18.224.65.226 >> ~/.ssh/known_hosts

      - name: Add StrictHostKeyChecking to SSH Config
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Your Other Steps
        run: |
          # Your other deployment steps here
          ssh admin@18.224.65.226 <<EOF
          mkdir pp
