name: Your Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEBIAN }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 3.15.17.62 >> ~/.ssh/known_hosts

      - name: Add StrictHostKeyChecking to SSH Config
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Your Other Steps
        run: |
          # Your other deployment steps here
          ssh admin@3.15.17.62 <<EOF
          sudo apt update
          mkdir pr
