name: Your Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ip_rsa
          chmod 600 ~/.ssh/ip_rsa
          ssh-keyscan -t 18.224.65.226 >> ~/.ssh/known_hosts

      - name: Your Other Steps
        run: |
          # Your other deployment steps here
          ssh admin@18.224.65.226 <<EOF
          cd
          mkdir pp
          EOF
